### ISSUE TITLE
Displaying non XR HTML5 content inside XR

### ISSUE THREAD

**Issue by pmanixxx** [immersive-web/proposals#11]
An easy possibility to render a HTML5 (non XR content) iframe or a similar solution inside XR which would be able to interact with via controllers could dramatically increase the XR adoption pace, encouraging and facilitating wide scale development and paving way for lots of use cases as well as becoming a transitional period solution.
- a multi tab big screen customizable HMD working space and web browser could be created for viewing current content until XR standards are fully developed and websites start having their XR version, 
- while being inside another app, instead of going out of VR mode when one needs to check something, a browser iframe would allow to do it there 
- direct benefactors could include all people working daily on multiple screens and multiple open tabs with limited table space
- while creating apps it would be easy to transfer existing content into XR mode
- a lot of people could start using HMDs instead of small screens in daily browsing as there is plenty of situations where it would be more practical for both VR and AR. 
- analytics would show, that increasing amount of content is being watched on HMDs and that developers need to address this use case, which would drive XR web standards adoption.

**Comment by johnpallett** [comment]
To clarify, this proposal is more than just rendering the DOM to a texture, it also includes an interactivity model for the DOM in AR/VR. Is that correct?

**Comment by pmanixxx** [comment]
Yes, correct. I see HMDs not only as app-specific gadget but as a natural evolution of screen, that we use today for everyday tasks and work. They will eventually match the resolution, image quality and comfort of use of monitors and they are already offering much more in terms of functionality. 
    
I imagine however that this might be split into two features - first - as you suggested - effectively being able to see the HTML/CSS/JS content, and second being able to interact with it the way we interact with content using current displays - desktop or mobile. In my opinion it is crucial for the period of transition., just like mobile devices are backward compatible by being able to display non-responsive websites in their desktop format. 
Such feature would render HMDs a fully functional browsing tools and speed up the technology adoption by offering important functionality. 
At present we have controllers, in the future we will probably have palms' movement tracking systems, but the model in which both interact with content might be developed earlier and upgraded later the same way as trackpads evolved.

**Comment by TrevorFSmith** [comment]
Is there more to discuss here or should I close this Issue?

**Comment by TrevorFSmith** [comment]
I'll close this now but feel free to reopen it if there is more discuss.
