### ISSUE TITLE
Define WebXR metadata

### ISSUE THREAD

**Issue by joshmarinacci** [immersive-web/proposals#21]
Pages should be able to add metadata which enhances the VR experience and provides information to search engines.  This data should specify:

* a 3D fav icon for use in bookmarks, tab headers, etc.
* a larger 2D splash image for use in catalogs 
* a preferred background skybox and/or 3d scene
* indicate if there is immersive content in this page. (it is webxr 'ready'?)

We should reuse existing open web metadata wherever possible.

and maybe other stuff like:
* indicate which input methods it supports
* a link to a WebXR version of the same content? (like link with rel)

and more?

**Comment by joshmarinacci** [comment]
I split these out into multiple issues.

**Comment by oscarmarinmiro** [comment]
@joshmarinacci Not to annoy you on a closed issue :-): I think your proposal makes a lot of sense, but could not find this split into other issues... do you have a link to any? 

(Came here from https://twitter.com/benz145/status/1228393301776072704 and thinking about how could we start to implement practices to make WebXR 'searchable')
