### ISSUE TITLE
define skybox images for a page

### ISSUE THREAD

**Issue by joshmarinacci** [immersive-web/proposals#23]
A page should be able to specify a 360 background image to be used as a skybox. Possibly also a GLTF scene, though that might have significant performance impacts.

This should probably be metadata at the top of the page, but we may need to handle multiple resolutions which implies working with the picture and img elements.

**Comment by joshmarinacci** [comment]
https://developer.samsung.com/internet/gearvr/web-guide

**Comment by TrevorFSmith** [comment]
Hey, folks. It seems like progress on this has stalled so I'm going to close it for now. If someone has a plan for making progress on this topic then let me know and we can re-open it.
