### ISSUE TITLE
Define a metadata element to indicate that a page is WebXR ready

### ISSUE THREAD

**Issue by joshmarinacci** [immersive-web/proposals#24]
A page author should be able to indicate if there is immersive content in this page. ie: is it 'webxr ready?'  This would be similar to how we can detect a mobile ready website by looking for the elements Apple specifies:

<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />

<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">

https://webkit.org/blog/7929/designing-websites-for-iphone-x/

**Comment by cvan** [comment]
to my knowledge, at least for WebVR v1.1, Firefox, Chromium/Chrome, Oculus Browser, Samsung Internet, and Edge infer a document is going to potentially enter VR when a WebVR-specific event listener (e.g., `window.addEventListener('vrdisplaypresentchange', …)`) is defined or `navigator.getVRDisplays` is called.

this changes for WebXR to be scoped under `navigator.xr`, but the same idea applies.

there's been proposals by myself, @caseyyee, @digitec, and others about having an `http-equiv` response header with a `<meta>` tag as fallback (à la mobile browsers' usage of `<meta name="viewport">`).

```http
XR-Content: true
```

```html
<meta http-equiv="XR-Content" content="true">
```

or to target the `<canvas>`:

```html
<meta http-equiv="XR-Content" content="#xr-canvas">
```

another idea I like is to use the `Link` header (a good example is in [GitHub's API](https://developer.github.com/v3/#pagination).

ultimately, I like the policy of not requiring the developer to define any `<meta>` tag or request header, but use [Resource Hints](https://w3c.github.io/resource-hints/) or similar for an improved user experience.

**Comment by cvan** [comment]
also, we should support web-app manifests as a place to define these capabilities: https://github.com/immersive-web/proposals/issues/22#issuecomment-416749744

the browser could prefetch the URLs, cache them, and know which sites are WebXR-ready.

**Comment by TrevorFSmith** [comment]
I suspect that this topic has been absorbed into the [navigation feature repo](https://github.com/immersive-web/navigation) so I'm going to close it. If you feel that this needs to be a separate conversation ping me and we can re-open it.
