### ISSUE TITLE
Create a metadata vocabulary for WebXR content

### ISSUE THREAD

**Issue by ronpadz** [immersive-web/proposals#32]
Establishing a shared metadata vocabulary for WebXR content will help machines (i.e. search engines) surface it in new and innovative ways. The vocabulary will be used by creators and publishers to reach an immersive experience-seeking audience by cutting through all the other noise on the web.

[Schema.org](https://schema.org/) vocabulary can be used with many different encodings, including RDFa, Microdata and JSON-LD. These vocabularies cover entities, relationships between entities and actions, and can easily be extended through a well-documented extension model. Schema.org vocabularies are developed by an open community process, using the public-schemaorg@w3.org mailing list and through GitHub.

Though it may not necessarily be appropriate for the vocabulary to be included in the WebXR Specification, it would behoove this community to actively collaborate on a vocabulary that will serve its needs and help advance adoption of the specification itself. I am proposing an initiative to establish THE WebXR vocabulary.

**Comment by TrevorFSmith** [comment]
It seems like forward motion on this topic has stalled so I'm going to close this Issue. If someone has a plan for how to move it forward then ping me and we can re-open it.
