### ISSUE TITLE
Capturing what's on the display

### ISSUE THREAD

**Issue by blairmacintyre** [immersive-web/proposals#36]
I'm wondering if we should consider having some methods for capturing what's on the display using the appropriate native APIs.

In Hololens, for example, it's possible to trigger a capture of the view (composited with the camera).  On Android and iOS, it's possible (in native apps) to use low level APIs to efficiently record what's on the display.  Same for Windows and MacOS.

There is a html-media-capture API for capturing an image from a camera, and it's possible to capture images from video if you have access via WebRTC.

But, in a discussion with some developers working with the various AR APIs (Google's WebAR and Mozilla's WebXR), as well as past discussions with folks using WebVR, it seems like it would be useful to have a way to capture an image or video of the view on the "current" display (compositing all layers and things like video that might not be available to the page).  

One could imagine those being saved and edited using native APIs (as is done in native apps), being made available to application-level "share sheets", and (for images at least) making them available to the javascript context (e.g., for use in the app, like uploading a thumbnail to a application server during a save, for example).

Obviously, such a capability would need to trigger a user-permission request.

I'm thinking about this here because we really want to leverage the native APIs tied to the AR/VR hardware.

**Comment by TrevorFSmith** [comment]
It seems like forward motion on this Issue has stalled so I'm going to close it. If you have a plan for how to make progress then ping me and we can re-open it.

**Comment by ddorwin** [comment]
See also the use cases in https://github.com/immersive-web/webxr/issues/694#issuecomment-501876257. There might also be some approaches related to Web Share for those particular use cases.

**Comment by sjcobb** [comment]
I'm sad to see discussion has stalled in this area (am I missing something?). This is the most important use-case for me currently, I'm working on a WebXR version of [this prototype](https://youtu.be/Sj6xeVoag3w). I can build it the traditional way I've been doing using desktop software like DaVinci Resolve to composite the video and ThreeJS scene together, but I hate camera tracking and was hoping to capture everything in real-time in AR. 

I know there are platform-specific ways to accomplish this goal, but I had frankly taken it for granted that this would be supported. Would building something at the library-level be a good approach (similar to this [j360 demo](https://github.com/imgntn/j360))? I'm thinking a module to use with Three.js when [xr renderer](https://threejs.org/docs/#api/en/renderers/WebGLRenderer.xr) is enabled, that allows you to record the full composited video or export out individual layers separately (if you want to apply different effects / color grading after the fact).

**Comment by cabanier** [comment]
The WebXR spec added support for [secondary views](https://immersive-web.github.io/webxr/#secondary-view) that are designed to capture output.
The idea is that the author can request them and if available they would render the scene to them but without controllers or other elements that are just for the primary viewer.
