### ISSUE TITLE
Ambisonics audio support

### ISSUE THREAD

**Issue by cwilso** [immersive-web/proposals#37]
It was suggested by the Web Audio WG that some form of element to support Ambisonics audio would be useful.  (Think of Ambisonics as a 3D audio codec, kind of like an audio-only skybox movie codec.)

**Comment by jgwinner** [comment]
Hi. Interesting question.

The problem with Ambisonics, as I understand it, is that it's "hard coded" for a fixed position listener. With Immersive Web, you want to be able to move around in the world. The audio may sound 'weird' if it's not translated properly. 

Granted, for something like 360 video, it would be fantastic (as long as the audio can do rotations). Checking [wikipedia](https://en.wikipedia.org/wiki/Ambisonics#Ambisonic_manipulation) it seems like rotations are possible but not sure about translations. 

My experience - immersive audio is the last great frontier, and not many people really understand it. I mention HRTF's to audio people and get blank looks.

We want to be able to walk around in our immersive worlds, and locate an object making noise with our eyes closed. I'd propose this as a minimum working spec. If Ambisonic sounds can do that, I'd be all for it.

What worries me, from talking to some audio people at VR mixers here in LA, is that they don't understand room scale, or properly localizing sounds during _**"playback".**_  I sort of get blank looks when I ask this question, but that is obviously very anecdotal. 

I think it's a great idea, as long as we can still walk around the world and not break immersion. Objects should be able to move around and also not break immersion. 

As a side note: I have often wondered if HRTF's could be eliminated by using a 5.1 or 4.1 setup, fixed location, in a room scale setup without headphones. This might be a perfect use for Ambisonics, if it's a seated immersive environment. 

I did a graph if sensory bandwidth for my book, and was intrigued to find that hearing isn't a high bandwidth sense. I think it's far more important for building a sense of immersion than people realize, and at least as powerful as vision in many ways. It requires some careful thought.

**Comment by TrevorFSmith** [comment]
It seems like forward motion on this Issue has stalled so I'm going to close it. If you have a plan for how to make progress then ping me and we can re-open it.
