### ISSUE TITLE
Support FaceDetector for AR

### ISSUE THREAD

**Issue by QingAn** [immersive-web/proposals#41]
For WebAR application, it is important to support human face detection through the mobile phone camera. Note that, this is not used for human face authentication, but just for returning the human face position. 

This includes the number of human faces detected, the relative position of human face within the camera's captured image, both 2D position (rectangle) and 3D position (matrix).

Therefore, a face detector API should be defined to support above function.

**Comment by TrevorFSmith** [comment]
It seems like forward motion on this Issue has stalled so I'm going to close it. If you have a plan for how to make progress then ping me and we can re-open it.
