### ISSUE TITLE
New Proposal: HTMLModelElement

### ISSUE THREAD

**Issue by grorg** [immersive-web/proposals#72]
# Title

`<model>` or `HTMLModelElement`

# Summary

Details found in [the explainer](https://github.com/WebKit/explainers/tree/main/model) on WebKit's repository.

# Example use cases

Also in [the explainer](https://github.com/WebKit/explainers/tree/main/model) on WebKit's repository.

# A rough idea or two about implementation

WebKit on iOS and macOS has an experimental implementation behind a flag.

**Comment by cabanier** [comment]
Do you have any examples I can try out?
Also, do I have to build WebKit myself or is this included in a public beta?

**Comment by AdaRoseCannon** [comment]
Repo here for continued work and discussion: https://github.com/immersive-web/model-element

Please update as needed.

**Comment by Yonet** [comment]
@grorg you are also one of the repo owners. Can you accept the invite so I can tag you in PRs. I can try re-sending if you need.
Also, is it OK to close this issue and continue the discussion on the model-element repo? Thanks!
