### ISSUE TITLE
Immersive-ar session for phone based AR headsets

### ISSUE THREAD

**Issue by HyroVitalyProtago** [immersive-web/proposals#81]
For now, `immersive-ar` sessions on phones is for normal usage (hand handled), but it would be interesting to allow a distinction between: `ar-session` (currently `immersive-ar`) and "real" `immersive-ar` sessions like in vr headset with passthrough capabilities with stereoscopic rendering that can be used with something like [zapbox](https://www.zappar.com/zapbox/).

**Comment by AdaRoseCannon** [comment]
This seems like something UAs could choose to do without needing to add anything to the standard
